### ISSUE TITLE
THRESH_TAP actual values and sensitivity

### ISSUE THREAD

**Issue by ABLomas** [wollewald/ADXL345_WE#10]
Trying to tune-up tap sensitivity using setGeneralTapParameters().
Defaults provided in example works (but are very sensitive). Going higher on numbers (3...16) did not provided me with result i need and i investigated datasheet:
`The THRESH_TAP register is eight bits and holds the threshold
value for tap interrupts. The data format is unsigned, therefore,
the magnitude of the tap event is compared with the value
in THRESH_TAP for normal tap detection. The scale factor is
62.5 mg/LSB (that is, 0xFF = 16 g)`
OK, so we have 1-byte value for THRESH_TAP - max 255/0xFF.
Looking into library:
`regVal = static_cast<uint16_t>(round(threshold / 0.0625));`
Here we cast value into 2-byte integer (?), so max value can be 4096. Where is second byte going?

Tried to set threshold value to ~4000 in setGeneralTapParameters() - and yes, sensitivity is now extremely low. 
But it's usable in very non-linear way. Maybe one byte is dropped?
In this way - isn't better to do cast into uint8_t then, as documentation requires (and change scale)?
Or there is something more going on?

**Comment by wollewald** [comment]
Well spottet: uint16_t is simply wrong. It should be:
regVal = static_cast<uint8_t>(round(threshold / 0.0625));

I will correct that. But it doesn't change anything. The upper byte is implicitely cut off.

**Comment by ABLomas** [comment]
Well, i tried to change into uint8_t and use range 0...16g (which after static_cast will return 0...254 dec).
values from 0 to 15 are approx the same - very sensitive.
Value "16" completely disables acc - no way to get interrupt working.
I will try values in between, but there is something going on for sure. Docs says:
`The activity, free-fall, and single tap/double tap detection functions without improved tap enabled
are performed using undecimated data. Because the bandwidth
of the output data varies with the data rate and is lower than
the bandwidth of the undecimated data, the high frequency and
high g data that is used to determine activity, free-fall, and single
tap/double tap events may not be present if the output of the
accelerometer is examined. This may result in functions triggering
when acceleration data does not appear to meet the conditions set
by the user for the corresponding function.`
So it may be that tap scale is completely non-linear and even unusable for real-world conditions as it is not tied to any acc measurements.

**Comment by wollewald** [comment]
I corrected the uint16_t issue. But as already mentioned this will not change anything. 

Choosing 16g as the TAP threshold will give 16/0.0625 = 256 for the threshold register. Since the register is 8 Byte, this will lead to a zero. The data sheet is not correct in this detail. If 0xFF represents 16g, the LSB is 0,062745..... 

I can't find anything that is wrong in the code that would explain non-linearity. Maybe it's really just a general issue with the design of the ADXL345.

**Comment by ABLomas** [comment]
I believe that there are some design issues with ADXL345.
Writing 254 value into register => no difference to any other, way too sensitive (the same as "1", "3" and anything else).
Writing 255 into register - disables acc, can't trigger even with plastic hammer.
So while values should be cast to 8b integer (at least for clarifying what they mean) - i believe that tap mode is not so configurable.
