### ISSUE TITLE
setFifoParameters overwrites FIFO_MODE

### ISSUE THREAD

**Issue by OLFDB** [wollewald/ADXL345_WE#3]
When using setFifoParameters after setFifoMode, the mode is overwritten to bypass.

Suggested fix:

```
void setFifoParameters(adxl345_triggerInt intNumber, uint8_t samples)
{
	regVal = readRegister8(ADXL345_FIFO_CTL);
	regVal &= 0b11000000;
	regVal |= (samples - 1);
	if (intNumber == ADXL345_TRIGGER_INT_2)
	{
		regVal |= 0x20;
	}
	writeRegister(ADXL345_FIFO_CTL, regVal);
}
```

**Comment by wollewald** [comment]
@OLFDB  You are right, this change can save much time for people who change the order and try find the reason why it's not working. I implemented your suggestion. Thanks for raising this issue!

**Comment by wollewald** [comment]
@OLFDB - Hi, I think this one can be closed, can't it?
