### ISSUE TITLE
"Tap mode" is not generating interrupts

### ISSUE THREAD

**Issue by ABLomas** [wollewald/ADXL345_WE#9]
Trying common ADXL345 module on Wemos D1, using I2C.
Readings work, all fine.
Trying ADXL345_single_tap.ino - and it does not generate interrupts on any bumps.
I started with basic example, then lowered sensitivity to 1.3g, increased duration, etc - by reading data i see that overloads up to 8g are registered, but INT2 (and INT1, too) do not change it's values.
I attached logic analyzer with trigger on INT1/INT2 pins and it confirms that values do not change.
I tested with another ADXL345 module - the same, interrupt pin value does not change on bumps.

Unrelated minor issues - to get example compiled under platformio + wemos D1 - need to move "tapISR" function to top of code (above setup()) and add ICACHE_RAM_ATTR in front of it.

**Comment by wollewald** [comment]
Hi @ABLomas, I can't reproduce the issue. I have just tried with a Wemos D1 mini board and the example ADXL34_single_tap.ino.

The only change I did to the sketch is changing the int2pin to D3 in line 14 and as you rightly mentioned the interrupt routine needs to be before setup and I added ICACHE_RAM_ATTR. I connected as follows:

G --> GND
5V -- > VCC
D1 --> SCL
D2 --> SDA
D3 --> INT2

With this setup I get tap interrupts. Be aware that the threshold of 3g shall only be exceeded for maximum of 30 milliseconds if you take the parameters I have chosen for the example. It's difficult to get an interrupt by shaking the module. I put the ADXL345 on a breadboard and a reliable method to get the tap interrupt is to let the breadboard fall from 1 cm height. Maybe you can try this or increase the duration in the function setGeneralTapParameters().

**Comment by ABLomas** [comment]
Ir's probably bad batch of ADXL345 or something (got 3 boards, all working but no interrupts, including activity/inactivity), so maybe not software issue (as i also can't get interrupts generated with other libs - tried after testing all 3 boards).
But still, where do you found D3 on wemos D1 mini board? https://www.wemos.cc/en/latest/d1/d1_mini.html
(i am using 4+5 as I2C link and 16 as interrupt - but also have LA attached with trigger trying to catch signal change)

EDIT: on older edition i see pin mapping: https://www.wemos.cc/en/latest/d1/d1_mini_3.1.0.html
So i will try to map to pin "0" (which is D3 in this case), but i guess LA would still notice change... Or trigger level change is extremely short and 24Msps is not enough?

**Comment by ABLomas** [comment]
Because on activity/inactivity sketch interrupts should still fire and do not require precise timing - yet those do not work too (the same as other lib), while i'm still getting axis positions (everything works except interrupts) - my guess that i got some bad boards.
Will close this issue as it's most likely completely unrelated, but if we are here - can you please check that markings on ADXL345 chip are similar to mine?
![adxl345](https://user-images.githubusercontent.com/8989151/223519423-05d12786-02f5-4932-b411-7ab96d064aa7.jpg)

**Comment by wollewald** [comment]
Your ADXL345 module looks like mine:

![image](https://user-images.githubusercontent.com/41305162/223539220-7e3ca4f8-43c6-45af-8de1-d040113f33ee.png)

And I had no problem to find D3 because the pins on the board are labelled accordingly:

![image](https://user-images.githubusercontent.com/41305162/223538986-6fb4620e-33d5-480f-9e97-748e5d4a460c.png)

**Comment by ABLomas** [comment]
Closed issue but i add some comments for future searches AND maybe code changes:
 - input pin (interrupt?) may be floating (and it is actually) so if (and it will) it triggers during startup - almost none of interrupt examples would work (as input pin will go high during startup and it won't be cleared). Solution - add "myAcc.readAndClearInterrupts();" to end of setup;
 - Wemos mini 4.0.0 is actually different from earlier versions, also no pin marking on silkscreen. 
On 4.0.0 if you plan to use serial, i2c and spi - you only have only one pin (16) remaining as INT input choice and pin 16 = digital pin 5 ("const int int2Pin = 5;" in examples). Pins 0/2 are shared and unsuitable for this purpose. **EDIT**: pin 16 does not support interrupts, so not possible at all (or do polling without interrupts)
 - ICACHE_RAM_ATTR is obsolete (?), use IRAM_ATTR

My 3x tested acc's appear to be working, just triggered way too early and nobody cleared interrupt register...

**Comment by wollewald** [comment]
Hi @ABLomas, thank you for the helpful comments!
